<div class="adminlogin-box">
    <div class="adminlogin-box-wrap">
        <div class="box-header stap-one-active">
            <div class="box-header-wrap">
                <div class="box-stap">
                    <span class="strat-box box-number">1</span>
                    <span class="end-box box-number">2</span>
                </div>
            </div>
        </div>
        <div class="adminloginlogin-body">
            <div class="adminloginlogin-body-wrap">
                <div class="box-icon-image">
                    <img src="<?= $block->getViewFileUrl('Ec_Qr::images/bag-icon.jpg');?>" alt="">
                </div>
                <h2><?= __('Video Gift Message App Set Up'); ?></h2>
                <p><?= __('Set your store price for each customer generated video gift message. Want to offer it for free? No problem, just set your price to $0'); ?></p>
                <div class="box-form-wrap">
                    <form action="<?= $block->getRegisterSuccessActionUrl(); ?>" method="post" class="tabform-wrap" enctype="multipart/form-data">
                        <?= $block->getBlockHtml('formkey') ?>
                        <div class="form-fild pricetext">
                            <!-- <label for="price"><?= __('price'); ?><span class="red">*</span></label>  -->
                            <input type="number" name="price" value="1.95" step="0.01" min="0" required>
                            <!--  <?= __("The following is based off your shop's default currency"); ?>
                            <span class="input-group-text" id="price-addon">.ec-hd-tst-svr.tk</span> -->
                        </div>
                        <div class="form-top-text">
                            <p><?= __("The following is based off your shop's default currency"); ?></p>
                        </div>
                        <div class="form-submitbtn">
                            <input id="submit" type="submit" value="Confirm" />
                        </div>   
                        <div class="form-bottom-text">
                            <p><?= __("Tip: Change at any time within your account settings"); ?> </p>
                        </div>   
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>