<div class="adminlogin-box">
    <div class="adminlogin-box-wrap">
        <div class="box-header stap-two-active">
            <div class="box-header-wrap">
                <div class="box-stap">
                    <span class="strat-box box-number">1</span>
                    <span class="end-box box-number">2</span>
                </div>
            </div>
        </div>
        <div class="adminloginlogin-body stap-two-active">
            <div class="adminloginlogin-body-wrap">
                <h2><?= __('Button Install Complete')?></h2>
                <p><?= __('This button has been installed on your cart page')?></p>
                <div class="box-form-wrap form-submitbtn">
                    <a href="<?= $block->getUrl("ecqr/config");?>"id="submit"><?= __('VIEW DASHBOARD')?></a>   
                </div>
            </div>
        </div>
    </div>
</div>