<?php $config = $block->getConfig();
if (!$config['key'] || !$config['secret'] || !$config['domain']) : ?>
    <div class="adminlogin-box">
        <div class="adminlogin-box-wrap">
            <div class="adminflexbox">
                <div class="col left-col">
                    <div class="col-wrap">
                        <div class="col-image-wrap">
                            <img src="<?= $block->getViewFileUrl('Ec_Qr::images/popup-image.png'); ?>" alt="no-image">
                        </div>
                        <div class="imgcol-text">
                            <h5><?= __('Giving your business the tools to deliver secure video experiences with ease!'); ?></h5>
                        </div>
                    </div>
                </div>
                <div class="col right-col">
                    <div class="col-wrap">
                        <div class="tabheader">
                            <ul class="adminlogin-tab">
                                <li class="admintab-list current" data-tab="Signup"><?= __('Register'); ?></li>
                                <li class="admintab-list" data-tab="Signin"><?= __('Sign In'); ?></li>
                            </ul>
                        </div>
                        <div class="admintabbody-text">
                            <div class="tabdetails current" id="Signup">
                                <div class="tabdetails-wrap">
                                    <div data-role="content" class="col-body">
                                        <form action="<?= $block->getRegisterActionUrl(); ?>" method="post" class="tabform-wrap" enctype="multipart/form-data">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="form-fild">
                                                <label for="email"><?= __('Email'); ?><span class="red">*</span></label>
                                                <input name="email" type="email" placeholder="Email" required />
                                                <input name="formtype" type="hidden" value="signup" />
                                            </div>
                                            <div class="form-fild domaintext">
                                                <label for="domain"><?= __('Domain'); ?><span class="red">*</span></label>
                                                <input name="domain" type="text" placeholder="Domain" required />
                                                <span class="input-group-text" id="domain-addon"><?= $block->getDomainUrl() ?></span>
                                            </div>
                                            <div class="form-submitbtn">
                                                <input id="submit" type="submit" value="Confirm" />
                                            </div>
                                            <div class="register-bottom-description">
                                                <p><?= __('Do you already have an account with Emotional Commerce?'); ?></p>
                                                <span data-tab="Signin" class="sign-login-link"><?= __('Log In'); ?></span>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="tabdetails" id="Signin">
                                <div class="tabdetails-wrap">
                                    <div data-role="content" class="col-body">
                                        <form action="<?= $block->getLoginActionUrl() ?>" method="post" class="tabform-wrap" enctype="multipart/form-data">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="form-fild">
                                                <label for="email"><?= __('Email'); ?><span class="red">*</span></label>
                                                <input name="email" type="email" placeholder="Email" required />
                                                <input name="formtype" type="hidden" value="login" />
                                            </div>
                                            <div class="form-fild">
                                                <label for="password"><?= __('Password'); ?><span class="red">*</span></label>
                                                <input name="password" type="password" placeholder="Password" required />
                                            </div>
                                            <div class="form-submitbtn">
                                                <input id="submit" type="submit" value="Log In" />
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
endif;
?>
