<div class="ec-form">
<div>
    <div data-role="collapsible">
        <div class="col-title" data-role="trigger">
            Instructions
        </div>
    </div>
    <div data-role="content" class="col-body">
        <p>
            <label for="key">Installation<span class="red">*</span></label>
        </p>
        <p>
            To add the "Add Popup" button on any page, just copy the below shortcode and simply place it inside your CMS page, Static block OR call using a widget,</br> and you can enable the Popup Button OR Banner without any custom coding and easily manage the behavior from the admin.<br />
            </br>
            <span class="red">{{block class="Ec\Qr\Block\Cart" template="Ec_Qr::dynamicbtn.phtml"}}</span> </br></br>
            To add  CMS page add the above code using the below step.</br></br> <span class="red">Login to the admin panel => Go to Content => Pages => Edit and Put the above copy code and Hit the Save button.</span></br></br> <span class="red">Please don't forget to flush the cache after save the shortcode in CMS Page, Static Block OR Widget.</span> </br></br></br>
            You can also Add the above short code inside the static block and call it anywhere on your website using Widget.
        </p>
    </div>
</div>
</div>
